language: objective-c

install:
  - brew install neko haxe
  - cd ..
  - mkdir haxelib
  - haxelib setup haxelib
  - haxelib install hxcpp 3.4.64 > /dev/null
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - sh test.sh